# Clase 2 - SQL con SQLAlchemy: almacenamiento y consulta desde Python

##  Teoría breve

En ciencia de datos, una vez que los datos han sido limpiados, es importante almacenarlos de manera que podamos consultarlos de forma eficiente y segura. Para eso usamos bases de datos relacionales.

### ¿Por qué usar bases de datos?

- Permiten almacenar datos limpios de forma persistente.
- Facilitan búsquedas, filtros y consultas específicas.
- Son escalables y permiten trabajar con grandes volúmenes de datos.
- Se integran bien con herramientas de análisis.

Usaremos **SQLite** como base de datos local, y la librería **SQLAlchemy** para conectar desde Python.

**SQLAlchemy:** Un motor de base de datos que permite comunicación con SQLite (o cualquier otro SGBD como MySQL, PostgreSQL, etc.) usando una misma interfaz.

### Instalación (si es necesario)

In [ ]:
!pip install sqlalchemy

## Creamos un DataFrame de ejemplo

In [1]:
import pandas as pd

data = {
    'nombre': ['Ana', 'Luis', 'Carlos'],
    'edad': [23, 35, 29],
    'ciudad': ['CDMX', 'Guadalajara', 'Monterrey']
}

df = pd.DataFrame(data)
df

   nombre  edad       ciudad
0     Ana    23         CDMX
1    Luis    35  Guadalajara
2  Carlos    29    Monterrey

## Crear conexión a SQLite y guardar el DataFrame

In [ ]:
from sqlalchemy import create_engine

# Crear motor de base de datos SQLite
engine = create_engine('mysql:///personas.db')

# Guardar el DataFrame como tabla 'personas'
df.to_sql('personas', con=engine, if_exists='replace', index=False)

3

## Leer desde SQLite con una consulta SQL

In [3]:
# Leer todos los datos
consulta = 'SELECT * FROM personas'
df_leido = pd.read_sql(consulta, con=engine)
df_leido

   nombre  edad       ciudad
0     Ana    23         CDMX
1    Luis    35  Guadalajara
2  Carlos    29    Monterrey

In [6]:
# Leer solo las personas mayores de 25 años
consulta = 'SELECT * FROM personas WHERE edad > 25'
df_leido = pd.read_sql(consulta, con=engine)
df_leido

   nombre  edad       ciudad
0    Luis    35  Guadalajara
1  Carlos    29    Monterrey